# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 08:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counties', models.CharField(max_length=25)),
                ('codes', models.IntegerField()),
                ('cty_code', models.CharField(max_length=24)),
                ('dis', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Fiberbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('village', models.CharField(blank=True, max_length=50, verbose_name='\u6751\uff08\u793e\u533a\u5c45\u59d4\u4f1a\uff09')),
                ('town', models.CharField(blank=True, max_length=50, verbose_name='\u4e61\u9547\uff08\u8857\u9053\u529e\u4e8b\u5904\uff09')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='\u4f4d\u7f6e')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'ordering': ('-updated_at',),
                'verbose_name': '\u5149\u7ea4\u7bb1',
                'verbose_name_plural': '\u5149\u7ea4\u7bb1',
            },
        ),
    ]
