# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 15:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiberboxes',
            options={'ordering': ('-created_at',), 'verbose_name': '\u5149\u7ea4\u7bb1', 'verbose_name_plural': '\u5149\u7ea4\u7bb1'},
        ),
        migrations.AlterField(
            model_name='fiberboxes',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='fiberboxes',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='fiberboxes',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='fiberboxes',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
