# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20180504_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiberboxes',
            options={'ordering': ('-updated_at',), 'verbose_name': '\u5149\u7ea4\u7bb1', 'verbose_name_plural': '\u5149\u7ea4\u7bb1'},
        ),
        migrations.AddField(
            model_name='fiberboxes',
            name='towns',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u4e61\u9547'),
        ),
        migrations.AddField(
            model_name='fiberboxes',
            name='village',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6751'),
        ),
    ]
