# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20180507_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberboxes',
            name='town',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u4e61\u9547\uff08\u8857\u9053\u529e\u4e8b\u5904\uff09'),
        ),
    ]
