# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20180507_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberboxes',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
